services:
  backend:
    build:
      context: ./backend
    container_name: esonero_backend
    working_dir: /app/backend
    command: uvicorn src.main:app --host 0.0.0.0 --port 8003 --reload
    ports:
      - "8003:8003"
    volumes:
      - ./backend:/app/backend
      - ./domains.json:/app/domains.json
      - ./gs_data:/app/gs_data
    environment:
      - PORT=8003
      - PYTHONUTF8=1
      - PYTHONPATH=/app/backend
    networks:
      - esonero_network
      
  frontend:
    build:
      context: ./frontend
    container_name: esonero_frontend
    ports:
      - "8004:8004"
    volumes:
      - ./frontend:/app/frontend
    environment:
      - BACKEND_URL=http://backend:8003
      - PYTHONUTF8=1
      - PYTHONPATH=/app/frontend
    depends_on:
      - backend
    networks:
      - esonero_network

networks:
  esonero_network:
    driver: bridge
